### PR TITLE
Management commands refactor

### PR DESCRIPTION
**Pull request by gordonje**
Work on #1178.

### CODE REVIEW

**Comment by gordonje** [comment]
(Changes related to #1181, #1182 and #1178) 

@bcipolli / @adborden / @aboutaaron: Y'all want to take a look at these changes to the management commands before we merge them?

In a nutshell, we are:
*    Splitting download functionality into it’s own leaner `downloadcalaccessdata` command. If need be, you can still subclass this new command and overwrite its url attribute if you need to re-purpose the logic for getting other data besides what's provide by CAL-ACCESS;
*    Renaming the old master command to `updatecalaccessrawdata` and removed some of the skip options.

There's also been a fair amount of renaming and moving around the command options, and there may still be more to come. But everything I've pushed up so far is passing our tests, and we feel like merging this before we dive into more of those tweaks.

**Comment by palewire** [comment]
Unless @bcipolli or others object, I think we should merge this today and push forward.

**Comment by bcipolli** [comment]
This is ok; a bit hard to review with non-command-related changes (looks like examples changed too?)

**Comment by palewire** [comment]
Yes the example TSVs have changed, but they are randomly generated anyway from the raw stuff so nothing much is different there.

**Comment by bcipolli** [comment]
Sure. I just meant that including them here makes the PR much harder to review.

**Comment by gordonje** [comment]
Yeah @bcipolli, that's my b. While running some tests, I unintentionally re-generated all those test data file and committed those changes. Sorry!

Here's a list of the files with changes that you probably care about:
*    calaccess_raw/management/commands/cleancalaccessrawfile.py
*    calaccess_raw/management/commands/downloadcalaccessrawdata.py
*    calaccess_raw/management/commands/loadcalaccessrawfile.py
*    calaccess_raw/management/commands/updatecalaccessrawdata.py
*    calaccess_raw/management/commands/verifycalaccessrawfile.py

**Comment by bcipolli** [comment]
Just to reiterate, I'm cool with whatever. If there's anything that doesn't jive, I can make a PR to discuss when we start refactoring from our side.

**Pull request merged**
