### PR TITLE
added cache to .travis.yml

### PR DESCRIPTION
**Pull request by Charlex**
for issue #103

### CODE REVIEW

**Comment by palewire** [comment]
Does this method work? Are you seeing reductions in the test times on TravisCI?

I assumed we'd have to switch to their [container service](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) and use the [cache option](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) that provided.

**Comment by Charlex** [comment]
I think I may have listed the wrong directory for site-packages:

-    `- /home/travis/virtualenv/python2.7/lib/python2.7/site-packages`
+    `- /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages`

I'm also trying out sudo: false to switch over to the container service.

**Comment by Charlex** [comment]
Well it certainly sped up `pip install -r requirements_dev.txt` to .37 seconds, citing reqs already being satisfied.

The issue is now with the commands in `script` which are not being found. I'm investigating, but at this point I'm not sure why that is. Possibly due to not having access to sudo? Not sure..

**Comment by palewire** [comment]
Are you sure it said 0.37 and not 37.0? Look at the most recent Travis build [here](https://travis-ci.org/california-civic-data-coalition/django-calaccess-raw-data/jobs/52673496#L95). The requirements install is taking 44 seconds and it appears there are numerous over-the-web downloads in the log, which I presume will disappear when we have this working.



I'm going to close this pull request for now, since the patch doesn't appear to be working. If I'm wrong, let me know and I'll merge you right away. If not, don't get discouraged. Keep on hacking in your fork it and ask for a pull again when you're sure it works. This isn't the place for experimentation.

**Comment by Charlex** [comment]
Gotcha. 

Yeah. It looks the turning off sudo turns on the cache, but breaks the run. It does get that the pip install down to 0.37 seconds, not 37 seconds.

This run is proof of that:
https://travis-ci.org/california-civic-data-coalition/django-calaccess-raw-data/jobs/52672414

**Comment by palewire** [comment]
You're right. You can also see a cache step added to the routine in the build you linked here.



What explains this weirdness? Does it cache on the first build with proper settings and the benefits aren't reaped until a second build perhaps? Something about sudo? Odd.

**Comment by Charlex** [comment]
My concern is that with sudo:true, these lines break down:

screen shot 2015-03-01 at 3 30 10 pm

**Comment by palewire** [comment]
Alright. Your mission, should you choose to accept it, is to figure out what's going on here and to come back with a proposal that works.

**Comment by Charlex** [comment]
Haha, Thanks Ben. I accept this mission.

Also, thank you for pointing out to me that pull requests aren't places for experiments. I had never had set up Travis CI on any of my own projects before and just thought that working inside of a pull request was the way to use Travis. Now I know. And I've set up my own tests independently and I have that warm fuzzy feeling inside knowing I learned something ;)

**Comment by palewire** [comment]
Oh yeah, no biggie. There's no way to test a cloud thing like Travis without some trial and error. You *should* be getting Travis builds automatically from your fork. If you're not you might need to link that up.

**Pull request closed without merging**
