### PR TITLE
STY: pep8 fixes

### PR DESCRIPTION
**Pull request by bcipolli**
For a reason I don't understand, `pep8` is passing in the main build but fails when I add a flag in my `resume` branch. When I run it locally on the `master` branch, I see a bunch of failures.

Resume branch failures (fewer than what I get in `master` branch when I run `pep8` locally)
image

I worked through the various `pep8` failures in the `master` branch, just submitting them here (and rebasing the `resume` branch on this)

### CODE REVIEW

**Comment by bcipolli** [comment]
It would be great to get this merged, so that future PRs will get more complete feedback on PEP8. I just rebased on master to take care of some more hidden PEP8 issues that came in with the last merge.

**Comment by gordonje** [comment]
@bcipolli looking at this one right now. We're getting a little annoyed with pep8 E501 re: line length. It's kind of a dumb to have to bust a url up onto two lines because harder to copy paste. I think we'll end up ignoring that rule. 

You mind taking care of that? I think it's just a matter of adding the ignore command to [tox.ini](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/tox.ini) then removing the unnecessary edits. Or just let me know if you would rather I do it. All this is helping me learn the codebase.

**Comment by bcipolli** [comment]
I personally find the line-length restriction to be really helpful in general. We could use #noqa on the URLs to ignore some of those lines.
But really, I'm fine whatever y'all want. I can make updates in about an hour. Shouldn't take long.

**Comment by gordonje** [comment]
Oh, so then we could just not apply the line length check to lines with the urls, right? That sounds like the way to go.

**Comment by palewire** [comment]
We could do that, or perhaps just bump up the line length checks to a more reasonable number like 100 or 120 or something.

**Comment by gordonje** [comment]
@palewire Are you worried about not applying other checks to these lines? If so, maybe the policy could be that #noqa's are only acceptable on lines that are also commented out, which is what were talking about for the vast majority of these lines containing urls.

Otherwise, what do we think would be a good cut off for line length?

**Comment by palewire** [comment]
I don't have an big problem with #noqa other than we might end up with dozens of them scattered all over our code. I'm curious if a default we all consider a little more sensible (120?) solves the problem all on its own.

**Comment by gordonje** [comment]
Yeah, I suppose remembering to add all those might also be a little annoying. 

Looks like the longest we are talking about are 95 chars. Round it up to 100? @bcipolli would the line length restriction still be helpful for you at that point?

**Comment by bcipolli** [comment]
Fine for me, let's try it! Good chance to figure out how sublime / `pep8` do config as well.

**Comment by gordonje** [comment]
Rad. I'll look for those changes from @bcipolli. Let me know if I can help (or if you would rather I handle it myself).

**Comment by bcipolli** [comment]
Super-easy--just add to `tox.ini`. `pep8` in Sublime follows it, so it's a per-project thing--awesome.

Just need to fix up the URLs in the stuff I already did, fix up the commits, and we'll be ready!

**Comment by bcipolli** [comment]
OK, updated, tests pass, URLs are all on one line now. I think this is good to go.

**Comment by gordonje** [comment]
Awesome. Thanks again @bcipolli

**Pull request merged**
