### PR TITLE
Add Python 3 support

### PR DESCRIPTION
**Pull request by myersjustinc**
Should take care of #77, even if it took a little longer than expected. Works on my installations of 2.7.8 and 3.3.5. (I should get around to updating those.)

Changes:

* Removed long literals (e.g., `max_length=55L`), which aren't a thing anymore.
* Used `io.StringIO` instead of `cStringIO.StringIO`, so strings of all flavors can be passed as arguments without a lot of juggling.
* Allowed Unicode to render properly in yes/no prompt at beginning of download process.
* Replaced model `__unicode__` methods with cross-compatible `__str__` equivalents per [the Django docs](https://docs.djangoproject.com/en/1.7/topics/python3/#str-and-unicode-methods).
* Used csvkit consistently throughout for Unicode-aware CSV handling.
* Ensured model/admin `__init__` imports worked consistently across versions.

### CODE REVIEW

**Comment by palewire** [comment]
Thanks for sticking with it! I'll download the code and give this a try.

**Comment by myersjustinc** [comment]
Glad to do it. I'm noticing on the current Travis build that it's failing on [Django 1.4](https://travis-ci.org/california-civic-data-coalition/django-calaccess-raw-data/jobs/53973717)--turns out Django doesn't support Python 3 [until 1.5](https://docs.djangoproject.com/en/1.7/topics/python3/).

Everything else is passing so far (but taking some time), but when it complains that the build failed, that's why. If you're OK with that, I can add another commit to this PR to get rid of the Django 1.4 test.

**Comment by palewire** [comment]
I'm working on that very issue right now. We don't need to support those old versions of Django so I'm going to cut the tests.

**Comment by myersjustinc** [comment]
Sounds good—I'll leave it alone, then.

**Comment by palewire** [comment]
In case you are curious, Travis has a "Matrix" setting that lets you omit certain envs for Python 3, [ala django-debug-toolbar](https://github.com/django-debug-toolbar/django-debug-toolbar/blob/master/.travis.yml#L14)

**Comment by myersjustinc** [comment]
Nice. First time using Travis, actually, so I'm still getting used to such things—but good to know!

**Comment by palewire** [comment]
You're in! Thanks again!

HERO

**Comment by myersjustinc** [comment]
You're welcome! Glad to help.

**Pull request merged**
