### PR TITLE
Sqlite support. Fixes #83.

### LINKED ISSUE #83: Add support for SQLite backend

### PR DESCRIPTION
**Pull request by hunterowens**
This commit adds and documents SQLite Support. SQLite3/Django really handled the datetimes without issue. The executemany hackery gives reasonable performance after I figured out how commit handling really worked and my old benchmark was stupid.

### CODE REVIEW

**Comment by palewire** [comment]
Thanks for moving ahead on this. I'm not sure I get everything about the code. 

For instance, why is the SQL template inside the loop by only used once? Is it be run again and again for no reason?

Also, why do I see the date and datetime field sorted out but never used?

Am I missing something?

**Comment by hunterowens** [comment]
Mostly confusing because I forgot to commit some cleanup on the code. A very minimalist version is attached, but I think I might be able to make it more robust.

**Comment by palewire** [comment]
Great. I still think that loop might be off. Isn't the SQL generated only once? Also, there is a merge conflict that I think is the new Postgres COPY trick.

**Comment by palewire** [comment]
I think because of the conflicts and the looping stuff I'm unsure about I'm going to close this for now.

**Pull request closed without merging**
