### PR TITLE
add test for two documents

### PR DESCRIPTION
**Pull request by lindzcook**
*check syntax errors/etc
*if additional documents, could create an array and loop through docs to check instead of having individual variables.

### CODE REVIEW

**Comment by gordonje** [comment]
@lindzcook Besides the missing colons, on the same two lines I replaced the `is` operator with `==`. In Python, `==` is how we test if two variables have the same value (i.e., equality), while `is` is how we test if they refer to the same object (i.e., identity), as explained [here](http://stackoverflow.com/questions/132988/is-there-a-difference-between-and-is-in-python). This wasn't obvious to me either, and I had to look up why it works this why.

All the other changes I've made deal with rather pedantic [PEP 8 style issues](https://www.python.org/dev/peps/pep-0008/). While these wouldn't keep your code from executing, they do cause our automated tests to fail, as we are using [this library](http://pep8.readthedocs.org/en/latest/) to assess which lines of code aren't adhering to the style guide.

Really impressive that you were able to bang this out in the time you had AND while coding blind in the browser without feedback from a console. Thanks again for coming to the code rush and taking this on. It's a huge help to us (me in particular).

**Comment by palewire** [comment]
Did you get a sticker? If not and you want one I will mail it to you. Just send me your address to ben.welsh@gmail.com.

**Comment by lindzcook** [comment]
Great -- glad it was useful. Thanks for the feedback! 

Lindsey Cook

**Comment by lindzcook** [comment]
I got one -- Thanks!

On Tue, Mar 15, 2016 at 1:36 PM, Ben Welsh <notifications@github.com> wrote:

> Did you get a sticker? If not and you want one I will mail it to you. Just
> send me your address to ben.welsh@gmail.com.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/california-civic-data-coalition/django-calaccess-raw-data/pull/1297#issuecomment-196940471>
>



-- 
Lindsey Cook
@lindzcook
*Subscribe to my newsletter, Up, Down, All Around
<https://tinyletter.com/UpDownAllAround>, to receive daily updates on
interesting data news*

**Pull request merged**
