### PR TITLE
Id columns included in models, and beginning of additional verifications...

### PR DESCRIPTION
**Pull request by rkiddy**
I am sure this my use of python idiom is not good, and there are definitely better ways to do some of this. But the verification shows you some things.

For example, see below. The backslash at the end of line 84793 is messing up the loading of the next line, so a row with id of 84793 does not appear in the table.

```
$ python manage.py verifycalaccessrawfile HdrCd
 Verifying HdrCd
  Table Record count doesn't match CSV or TSV.
    table # 638389  CSV # 638390  TSV # 638390
    ids: [84793]

    hdr: id\tFILING_ID\tAMEND_ID\tREC_TYPE\tEF_TYPE\tSTATE_CD\tCAL_VER\tSOFT_NAME\tSOFT_VER\tHDRCOMMENT\r\n
    tsv: 84792\t937738\t0\tHDR\tCAL\tCA\t2.01\tCOMPLETECAMPAIGNS.COM\t1.00\\\t\r\n
    tsv: 84793\t930987\t1\tHDR\tCAL\tCA\t2.01\tNETFILE\t1611\t\r\n
    tsv: 84794\t937770\t0\tHDR\tCAL\tCA\t2.01\tEASYDISCLOSURE.COM\t1.00\t\r\n
```
In my scripts, I found it most useful to store info about the differences and then use another script to display the differences. Sometimes it is useful to see one-line on a line, as I have it above, but sometimes it is useful to break each line into the separate column values and that sometimes make the error more obvious.

For example, see below. I think the problem is from the middle row, where there seems to be a tab in the middle of a name:
```
\tSteve Mohr,\t Senior Vice President/CFO\t
```
But one would have to see which value corresponded to which column header to see where the problem lies.

```
$ python manage.py verifycalaccessrawfile CvrCampaignDisclosureCd
 Verifying CvrCampaignDisclosureCd
  Table Record count doesn't match CSV or TSV.
    table # 330593  CSV # 330594  TSV # 330602
    ids: [340, 471, 731, 1781, 109223, 155368, 167226, 276377, 318903]
...
    hdr: id\tFILING_ID\tAMEND_ID\tREC_TYPE\tFORM_TYPE\tFILER_ID\tENTITY_CD\tFILER_NAML\tFILER_NAMF\tFILER_NAMT\tFILER_NAMS\tREPORT_NUM\tRPT_DATE\tSTMT_TYPE\tLATE_RPTNO\tFROM_DATE\tTHRU_DATE\tELECT_DATE\tFILER_CITY\tFILER_ST\tFILER_ZIP4\tFILER_PHON\tFILER_FAX\tFILE_EMAIL\tMAIL_CITY\tMAIL_ST\tMAIL_ZIP4\tTRES_NAML\tTRES_NAMF\tTRES_NAMT\tTRES_NAMS\tTRES_CITY\tTRES_ST\tTRES_ZIP4\tTRES_PHON\tTRES_FAX\tTRES_EMAIL\tCMTTE_TYPE\tCONTROL_YN\tSPONSOR_YN\tPRIMFRM_YN\tBRDBASE_YN\tAMENDEXP_1\tAMENDEXP_2\tAMENDEXP_3\tRPT_ATT_CB\tCMTTE_ID\tREPORTNAME\tRPTFROMDT\tRPTTHRUDT\tEMPLBUS_CB\tBUS_NAME\tBUS_CITY\tBUS_ST\tBUS_ZIP4\tBUS_INTER\tBUSACT_CB\tBUSACTVITY\tASSOC_CB\tASSOC_INT\tOTHER_CB\tOTHER_INT\tCAND_NAML\tCAND_NAMF\tCAND_NAMT\tCAND_NAMS\tCAND_CITY\tCAND_ST\tCAND_ZIP4\tCAND_PHON\tCAND_FAX\tCAND_EMAIL\tBAL_NAME\tBAL_NUM\tBAL_JURIS\tOFFICE_CD\tOFFIC_DSCR\tJURIS_CD\tJURIS_DSCR\tDIST_NO\tOFF_S_H_CD\tSUP_OPP_CD\tEMPLOYER\tOCCUPATION\tSELFEMP_CB\tBAL_ID\tCAND_ID\r\n
...
    tsv: 276376\t1819136\t0\tCVR\tF460\t1353812\tCTL\tJONES-SAWYER FOR ASSEMBLY 2014\t\t\t\t000\t1/31/2014 12:00:00 AM\tSA\t\t7/1/2013 12:00:00 AM\t12/31/2013 12:00:00 AM\t\tLOS ANGELES\tCA\t90010\t213-489-4792\t213-489-4818\tdlgould@davidgouldcomapny.com\t\t\t\tGould\tDavid L.\t\t\tLos Angeles\tCA\t90010\t213-489-4792\t\t\tC\tY\tN\tN\tN\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tJones-Sawyer\tReginald B.\t\t\tLos Angeles\tCA\t90010\t213-489-4792\t213-489-4818\tdlgould@davidgouldcompany.com\t\t\t\tASM\t\tASM\t\t59\tS\t\t\t\t\t\t\r\n
    tsv: 276377\t1819137\t0\tCVR\tF461\t484219\tMDI\tLoma Linda University Medical Center\t\t\t\t000\t1/21/2014 12:00:00 AM\t\t\t1/1/2013 12:00:00 AM\t12/31/2013 12:00:00 AM\t\tLoma Linda\tCA\t92354\t(909) 558-4728\t\t\t\t\t\tSteve Mohr,\t Senior Vice President/CFO\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tX\tHospital/Health Care\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n
    tsv: 276378\t1819163\t0\tCVR\tF460\t1353849\tCTL\tGALGIANI FOR SENATE 2016\t\t\t\t000\t1/30/2014 12:00:00 AM\tSA\t\t7/1/2013 12:00:00 AM\t12/31/2013 12:00:00 AM\t6/7/2016 12:00:00 AM\tLos Angeles\tCA\t90010\t213 489-4792\t213 489-4818\tdlgould@davidgouldcompany.com\t\t\t\tGould\tDavid\t\t\tLos Angeles\tCA\t90010\t213 489-4792\t\t\tC\tY\tN\tN\tN\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tGalgiani\tCathleen\t\t\tManteca\tCA\t95336\t213 489-4792\t213 489-4818\t\t\t\t\tSEN\t\tSEN\t\t5\t\t\t\t\t\t\t\r\n
```

### CODE REVIEW

**Comment by rkiddy** [comment]
A few things to note.

I am not yet understanding how to pass flags and options down to the proper places, so when I figure this out, there would be a verbose flag and such as that.

Also, just fyi, when I run the verify on RcptCd, it totally hangs my computer. Ick. There is obviously an optimization needed here.

**Comment by rkiddy** [comment]
I took out all the stuff that was trying to read the lines in the TSV file and the CSV file and am storing the missing lines in a "verification" table. Another command, or the verify command called with different flags, can read this data and get the text files and do either just the lines, or breaking out all the values depending on how the flags passed.

**Comment by rkiddy** [comment]
It is interesting that it is fairly easy to look at the number of rows in the tsv file, the csv file and the database and see that there is a problem of some kind, but it is surprisingly hard to see exactly which lines have the problem or what the problems are. For example, this line in the DEBT_CD.TSV files throws off my identification of the line with the problem:
```
$ awk 'BEGIN{FS="\t"}{if ($1 == "47254") print $0}' tsv/DEBT_CD.TSV | od -c
0000000   4   7   2   5   4  \t   8   7   1   7   7   3  \t   1  \t   6
0000020   9  \t   D   E   B   T  \t   F  \t   P   A   Y   6   3   5   4
0000040   1  \t   O   T   H  \t   C   o   r   p   o   r   a   t   e    
0000060   E   x   p   r   e   s   s  \t  \t  \t  \t   S   a   n   t   a
0000100       F   e       S   p   r   i   n   g   s  \t   C   A  \t   9
0000120   0   6   7   0  \t   0  \t   6   1   3   .   7   3  \t   0  \t
0000140   6   1   3   .   7   3  \t   O   F   C  \t  \t  \t  \t  \t  \t
0000160  \t  \t  \t  \t  \t  \t  \t  \t  \r  \r  \n
```
Note the line ending, which is "\r\r\n".

I am tempted to suggest that we need a separate command (or an option on the verify) which takes a cvs file and turns it into another copy of the tsv file that produced it, and another that gets the db data and turns it into the csv file. Then we could say that if there is a problem, generate the corresponding file and see where it different. After all, if there is no problem, then one should be able to reproduce the exact same tsv from the csv file and the exact same csv file from the database.

**Comment by rkiddy** [comment]
Does anyone have any suggestions for me at this point? This pull-request has been a way for me to figure some things out, obviously. But I believe that something has gelled. What does this do?

1) add the id column to the TSV, which get propagated into the database tables.
2) add a bit to the verify command so that a "derived" TSV is re-constructed from the database tables.
3) there is no number 3 

Right now, the derived TSV will be useful but not always as useful as we would hope. But it certainly does not hurt. And, after all, the verify command is not automatically run. I think it should be, but that will be the subject of a separate pull-request.

I think my code is not as careful about memory use as it should be. My laptop gets hung up, for example, by verifying the expn table. But I can fix that. If I do fix that and do nothing else, can this pull-request be wrapped up and merged? I should be able to correct the merge conflicts. Is there anything else that people are concerned about? If so, please let me know.

**Comment by aboutaaron** [comment]
My current concern is handling ids explicitly in Django. I totally agree with why we should add them explicitly, but I want to make sure it doesn't break any other dependencies, namely `django-calaccess-campaign-browser`. @palewire thoughts?

**Comment by rkiddy** [comment]
The id column in the table is the same id column whether the id values some in with the import or get set via automatic key generation. And the tables already exist before the browser project kicks in. So, this change is below the notice of that project.

**Comment by rkiddy** [comment]
@palewire, I was wondering, can this be merged now? I have made the new functionality conditional on both the --create-diff and --missing-ids flags. There are still inefficiencies in running these (or I see them on my laptop) on the large files, expn, rcpt and such. But I would ask that this version be merged so that managing the code is simpler. Please. :-)

If you run the verify command without the new flags, it is AFAIK exactly as fast as it used to be. So it is safe, no?

Also, I checked on the issue I had with the unicode literals. See http://stackoverflow.com/questions/6625782/unicode-literals-that-work-in-python-3-and-2. Do you think something should be done in this code? Note that it is being suggested that the problem with the literals goes away with python 3.3.

**Comment by palewire** [comment]
I'll try to take a look at it soon. Sorry to have let it hang.

**Comment by palewire** [comment]
Explain to me why you need to add ``id`` fields for all the models? Django does that magically in the background [by default](https://docs.djangoproject.com/en/1.8/topics/db/models/#automatic-primary-key-fields). Am I missing something?

**Comment by aboutaaron** [comment]
I believe this was done so that the ids match the rows in the csv. Therefore we could have 1-to-1 matches for each object in the db with the csvs. I think this was to lay the groundwork for verification on data against the csvs we're parsing. I'm sure @rkiddy can explain more but that's what I understood the use case was. 

-----
Aaron Williams
Journalist/Developer
@aboutaaron




On Wed, Apr 22, 2015 at 9:49 PM -0700, "Ben Welsh" <notifications@github.com> wrote:












Explain to me why you need to add id fields for all the models? Django does that magically in the background by default. Am I missing something?

**Comment by rkiddy** [comment]
@palewire, you are right that django can add ids automatically. But these model changes tell django not to do that. :-)

The point is that unless there are id values that connect the data in the database to the data in the TSV, then one cannot see where the errors come from. Say there is a line that ends in a back-slash so that it messes up the loading of the line. The names in that line may be very common. You can try to search for them in the file and try to figure out which line has the problem, but it is complicated to do so.

It is very simple to add id values to the TSV files and it makes it immediately obvious how to connect the database rows and the TSV lines. And adding the id values in this way has no effect on the rest of the app.

**Comment by palewire** [comment]
Hmm. Convince me we need all this overhead for the problem. I look at the errors currently logged and see a short list. Couldn't we debug the error types based on [the logs](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/tree/master/example/test-data/log) and come up with nuances inside our loader the negate the need for all this?

**Comment by rkiddy** [comment]
```
$ cd ccdc/data/logs/
$ wc -l *
     10 cvr2_campaign_disclosure_cd.errors.csv
     2 cvr2_registration_cd.errors.csv
    10 cvr_campaign_disclosure_cd.errors.csv
    71 cvr_lobby_disclosure_cd.errors.csv
     2 cvr_registration_cd.errors.csv
    12 debt_cd.errors.csv
   280 expn_cd.errors.csv
    66 filername_cd.errors.csv
    17 lccm_cd.errors.csv
    11 lemp_cd.errors.csv
   102 lexp_cd.errors.csv
    13 loan_cd.errors.csv
    92 lpay_cd.errors.csv
    44 names_cd.errors.csv
    65 rcpt_cd.errors.csv
     4 s401_cd.errors.csv
    29 s496_cd.errors.csv
     3 s497_cd.errors.csv
     2 s498_cd.errors.csv
    60 text_memo_cd.errors.csv
```
Well, something seems to be making those logs less useful than they might be.... :-)

Perhaps you are right, though. Having a trackable connection between the line as it is in the TSV and the data as it appears or does not appear in the database makes it easier for me to track things. But I did this in my own version of the project, so of course I would be in favor of it.

I would not be terribly upset if we decided that this pull-request was just the way I learned to manipulate the project and that it can be closed.

Even without this, the verify could be smarter, the logging could probably be better (for example, it does not catch the issue I found in the hdr_cd.tsv file), and the unit tests can probably catch things also. And all of these would be separate and separable changes.

To me, it makes sense to have id values in the TSV files. It does give you a clear connection between the data file and the database and it is always better, IMHO, to have information and perhaps not use it right now, than to have no way to get the information.

But if you feel you wish to close this, I can address the other issues in more targeted edits and I would not be upset about it. Your call.

**Comment by palewire** [comment]
Thanks for the right numbers. Though even 895 bum rows are only 0.0025% of the 36 million rows in the database. I'm reluctant to slow down our loader and complicate our database just for them. I wonder if by studying your logs we can instead figure out a common pattern among the bad rows that we can solve.

**Pull request closed without merging**
