### PR TITLE
Added docstring for address.

### PR DESCRIPTION
**Pull request by Fagerlise**

### CODE REVIEW

**Comment by palewire** [comment]
You won a swaglode prize! Report to the Atrium bar to pick it up or contact me now!

**Comment by Fagerlise** [comment]
Fun😄👍 Where Are you?
Lise

Sendt fra min iPhone

Den 7. mar. 2015 kl. 18.56 skrev Ben Welsh <notifications@github.com<mailto:notifications@github.com>>:


You won a swaglode prize! Report to the Atrium bar to pick it up or contact me now!

**Comment by palewire** [comment]
If you come to M102 before the 9am classes start you can pick up your prize.

**Comment by Fagerlise** [comment]
Great😄

Sendt fra min iPhone

Den 8. mar. 2015 kl. 08.22 skrev Ben Welsh <notifications@github.com<mailto:notifications@github.com>>:

If you come to M102 before the 9am classes start you can pick up your prize.

**Pull request merged**
