### PR TITLE
Single build command, clearer and not stuck into download command

### PR DESCRIPTION
**Pull request by rkiddy**
A work in progress. See https://github.com/california-civic-data-coalition/django-calaccess-raw-data/issues/260

### CODE REVIEW

**Comment by palewire** [comment]
What is "only_tables?"

**Comment by rkiddy** [comment]
If you want to process only one or some number of tables, you call it with those tables.

The other commands take a table name as a label, yes? But I did not see an option for limiting the number of tables you are working on, except that you can call all the commands directly.

An example invocation would be:
```
python manage.py buildcalaccessrawfile --only-tables CvrSoCd,HdrCd
```

**Comment by rkiddy** [comment]
I am not sure why this is causing a problem with 'make docs'. I have installed Sphinx. I have tried to install sphinx-autobuild. It says that it installs the command. Where does it install it? I cannot find it. Neither can make. Yet, when I try to install it again, it says "oh no, you already have it." But it does not tell me where it is....

**Comment by rkiddy** [comment]
Hm. I did not touch the example/manage.py file and I see it there in my branch. Any suggestions about this? A bit cranky, isn't it?

**Comment by palewire** [comment]
Unless I'm missing something, this suggested patch is incomplete so I am going to close it pending further revision.

**Pull request closed without merging**
