### PR TITLE
form type choices

### PR DESCRIPTION
**Pull request by JoeGermuska**
Is this what you had in mind for #98, #99, #100 ? If so, I can carry on with #86, #87, #88, #89, #90, #91, #92, #93, #94, #95, #96

### CODE REVIEW

**Comment by JoeGermuska** [comment]
The `__unicode__` methods are gravy, but they seemed straightforward and helped my eyes from glazing over looking at the admin tool to make sure things were basically working. I figured safest to only use non-null fields, although at a glance, filer names, dates and such might be more attractive.

**Comment by palewire** [comment]
Yes. That's the kind of thing we're after, though our prissy PEP8 validator doesn't like the line lengths (no biggie) so the TravisCI test is failing. 

If you want to mow through them all that's great. I can always come up with more tickets!

**Comment by JoeGermuska** [comment]
the day slipped away, so we'll see. It's also the case that now that a model is set they are super easy for newbs to pick up.

**Comment by palewire** [comment]
Cool. Thanks man. You're [on the list](https://docs.google.com/spreadsheets/d/1CJPbxVKCqdrI_U6YKNnRkt8Kd-T-_CX7pNbmzgzmm3Q/edit)!

**Pull request merged**
